# Generated by Django 2.2.1 on 2019-07-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
