# Generated by Django 2.2.1 on 2019-07-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_db', '0002_auto_20190711_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
