# Generated by Django 2.2.1 on 2019-07-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_db', '0003_project_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
