# Generated by Django 2.2.1 on 2019-07-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_db', '0004_auto_20190711_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='samples',
            field=models.ManyToManyField(blank=True, through='data_db.ProjectSample', to='data_db.Sample'),
        ),
        migrations.AddField(
            model_name='projectsample',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_db.Project'),
        ),
        migrations.AddField(
            model_name='projectsample',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_db.Sample'),
        ),
    ]
